version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "next"
    versioning-strategy: "increase"
    directory: "/packages/cache-memory"
    schedule:
      interval: "daily"
    groups:
      minor-dependencies:
        update-types:
            - "minor"
            - "patch"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    target-branch: "next"
    versioning-strategy: "increase"
    directory: "/packages/featureserver"
    schedule:
      interval: "daily"
    groups:
      minor-dependencies:
        update-types:
            - "minor"
            - "patch"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    target-branch: "next"
    versioning-strategy: "increase"
    directory: "/packages/core"
    schedule:
      interval: "daily"
    groups:
      minor-dependencies:
        update-types:
            - "minor"
            - "patch"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    target-branch: "next"
    versioning-strategy: "increase"
    directory: "/packages/logger"
    schedule:
      interval: "daily"
    groups:
      minor-dependencies:
        update-types:
            - "minor"
            - "patch"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    target-branch: "next"
    versioning-strategy: "increase"
    directory: "/packages/output-geoservices"
    schedule:
      interval: "daily"
    groups:
      minor-dependencies:
        update-types:
            - "minor"
            - "patch"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    target-branch: "next"
    versioning-strategy: "increase"
    directory: "/packages/winnow"
    schedule:
      interval: "daily"
    groups:
      minor-dependencies:
        update-types:
            - "minor"
            - "patch"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    target-branch: "next"
    versioning-strategy: "increase"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-dependencies:
        update-types:
            - "minor"
            - "patch"
    rebase-strategy: "auto"
