version: 2
updates:
- package-ecosystem: "npm"
  directory: "/packages/cache-memory"
  schedule:
    interval: "weekly" 
- package-ecosystem: "npm"
  directory: "/packages/featureserver"
  schedule:
    interval: "weekly"
- package-ecosystem: "npm"
  directory: "/packages/koop-core"
  schedule:
    interval: "weekly"
- package-ecosystem: "npm"
  directory: "/packages/logger"
  schedule:
    interval: "weekly"
- package-ecosystem: "npm"
  directory: "/packages/output-geoservices"
  schedule:
    interval: "weekly"
- package-ecosystem: "npm"
  directory: "/packages/winnow"
  schedule:
    interval: "weekly"
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"