name: Create PR to find diff from master to next
on:
  push:
    branches:
      - master
jobs:
  masterToNext:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: next
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: master-to-next
          title: Re-sync "next" to "master" branch
          body: |
            There has been a push to "master" with changes, not represented in "next".  This can happen on direct pushes to "master" or on PRs that merge to master instead of "next" as an intermediate step.

            If "next" has commits/changes that are not in "master", you can try (1) merging this PR or (2) rebasing "next" with master.