name: Create next-branch pull request
on:
  push:
    branches:
      - next
jobs:
  nextToMaster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Reset promotion branch
        run: |
          git fetch origin next:next
          git reset --hard next
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: next-to-master
          title: Merge "next" into master
          body: |
            The "next" branch accumulates changes (dependency updates or other PRs) that will go into the next Koop release.  Merging this PR will trigger a new Koop release so long as at least one changeset file is present.